# Global settings for backtests & alerts
rules:
  data:
    years: 10
    interval: "1wk"
    min_bars: 120     # require >= ~2.3 years of weekly history

  rsi:
    enabled: true
    period: 14
    oversold: 30
    overbought: 70

  sma_cross:
    enabled: true
    short: 50
    long: 200

  price_vs_sma200:
    enabled: true
    near_pct: 5.0     # treat as "near" 200w within ±5%
    break_pct: 8.0    # deep break beyond ±8%

events:
  window_days: 14     # event must be within ±N days of the technical trigger date to count as “aligned”
  # CSVs live under data/
  equity_csv: "data/events_equity.csv"
  btc_csv: "data/events_btc.csv"
  xrp_csv: "data/events_xrp.csv"
