name: Backtest S&P500 (10y) with Events

on:
  workflow_dispatch: {}

jobs:
  backtest:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -V
          pip freeze | sed -n '1,80p'

      - name: Run backtest (and always produce an artifact)
        env:
          CONFIG_PATH: config.yaml
        run: |
          set -euxo pipefail
          mkdir -p out
          echo "artifact heartbeat $(date -u +"%Y-%m-%d %H:%M:%S UTC")" > out/heartbeat.txt
          echo ">>> repo tree (before run)" > out/log.txt
          ls -la >> out/log.txt
          echo ">>> starting script" >> out/log.txt
          python backtest_events.py 2>&1 | tee -a out/log.txt || true
          echo ">>> repo tree (after run)" >> out/log.txt
          ls -la >> out/log.txt
          echo ">>> out/ listing" >> out/log.txt
          ls -la out >> out/log.txt || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sp500-backtest-with-events
          path: out/**
          if-no-files-found: warn
