name: Backtest S&P500 (10y) with Events

on:
  workflow_dispatch: {}

jobs:
  backtest:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -V

      - name: Run backtest (SPY via Alpha Vantage API, fallback to yfinance)
        env:
          CONFIG_PATH: config.yaml
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
        run: |
          set -euxo pipefail
          mkdir -p out
          python backtest_events.py
          echo ">>> list out/"
          ls -la out

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sp500-backtest-with-events
          path: out/**
          if-no-files-found: warn
