name: Backtest S&P500 (10y) with Events

on:
  workflow_dispatch: {}   # manual run from Actions tab

jobs:
  backtest:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backtest (S&P 500 + Events)
        env:
          CONFIG_PATH: config.yaml
        run: |
          python backtest_events.py
          echo "---- Listing output folder (if any) ----"
          ls -la || true
          echo "---- Listing ./out ----"
          ls -la out || true

      # Upload EVERYTHING inside the out/ folder, whatever the filenames are
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sp500-backtest-with-events
          path: out/**
          if-no-files-found: warn
