name: Backtest S&P500 (10y) with Events

on:
  workflow_dispatch: {}   # manual run from Actions tab

jobs:
  backtest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backtest (S&P 500 + Events)
        env:
          CONFIG_PATH: config.yaml
        run: |
          python backtest_events.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sp500-backtest-with-events
          path: |
            out/sp500_backtest_triggers_with_events.csv
            out/sp500_backtest_summary_with_events.txt
